language: python
python:
  - "2.7"
jdk:
  - openjdk7
virtualenv:
  system_site_packages: true
install:
  # Install Spark
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-1.1.0-bin-hadoop2.4.tgz
  - tar -xzf http://d3kbcqa49mib13.cloudfront.net/spark-1.1.0-bin-hadoop2.4.tgz
  - sudo apt-get install -qq python-numpy python-scipy python-pandas python-sklearn
  - pip install -r requirements.txt
  # Workaround for Travis issue with POSIX semaphores; see
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
script:
    - export SPARK_HOME=`pwd`/spark-1.1.0-bin-hadoop2.4
    - cd test
    - ./run_tests.sh
