language: python
python:
- '2.7'
jdk:
- openjdk7
before_install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
install:
- conda create --yes -q -n test-environment python=$TRAVIS_PYTHON_VERSION nose numpy
  scipy scikit-learn scikit-image matplotlib
- source activate test-environment
- pip install -r requirements.txt
- wget http://d3kbcqa49mib13.cloudfront.net/spark-1.3.1-bin-hadoop2.4.tgz
- tar -xzf spark-1.3.1-bin-hadoop2.4.tgz
- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
- export SPARK_HOME=`pwd`/spark-1.3.1-bin-hadoop2.4
- "./runtests.sh"
notifications:
  hipchat:
    rooms:
      secure: aLwgryE6o1TzwbCu9zaf6XdtQS7u7VZv7C5HY8zcpUgNBLmPUTJax/WgU3n259P4YRdHitpdgUPZeeCOY7hcOBC9uztfbE6ChI0A8fnz3ClWnOsKdo+sqFa29Jy+2KMcABxsLweLnMyJeVJdOO9o0Z9U3CKF+6iir/WCzVa7Ln0=
